### ISSUE TITLE
Familjeliv message posting bug

### ISSUE THREAD

**Issue by Ripipip** [adfenix/orator#1]
Orator url: http://www.orator.se/user-area/thread?id=200000171119&pg=2

Original url: http://www.familjeliv.se/forum/thread/74708364-vad-hander-om-vi-separerar-och-bor-30-mil-ifran-varandra-med-barn

Message: De omständigheter du nämner behöver inte nödvändigtvis påverka barnets lycka - tror nog du bara får acceptera att barnet bor där barnet är fram tills att det blir tillräckligt gammalt för att bestämma själv. 

Error message: none

**Comment by atifsheikh** [comment]
Need another Message text for this bug fixing.

**Comment by Ripipip** [comment]
Orator url: http://www.orator.se/user-area/thread?id=200000202542&pg=1

Original url: http://www.familjeliv.se/forum/thread/74734287-varfor-ar-svenska-killar-sa-fula-nar-svenska-tjejer-ar-snygga

Message: Haha! Det här var ju inte alls en generaliserande diskussion... Men om det är ett stort problem så kan du ju alltid bara norpa en icke-svensk man? Svårt att förstå diskussionsvärdet i detta. 

Error message: none

**Comment by atifsheikh** [comment]
Posting message is fixed now. Just need to upload the code.
