### ISSUE TITLE
Familjeliv discussion posting bug

### ISSUE THREAD

**Issue by Ripipip** [adfenix/orator#2]
Report formatting for post discussion bugs: 

Orator url: http://www.orator.se/user-area/create?forum=1103&category=1103107

Title: Vill inte bli Pappa!

Message: Så helt plötsligt från ingenstans kommer flickvännen och meddelar att hon är i 12e veckan och ska behålla barnet! Finns det något lagligt sätt jag kan undvika att bli Pappa? Känner mig inte alls redo för detta...  

Error message: none

**Comment by atifsheikh** [comment]
Need another Title and message to modify & test the code. 
(First one is used in Fiddler)

**Comment by Ripipip** [comment]
Orator url: http://www.orator.se/user-area/create?forum=1103&category=1103181

Title: Gifta sig enbart pga ekonomi? 

Message: Har alltid varit ganska osäker på giftermål men nu när barn är införskaffat så börjar flickvännens ekonomiska argument att bita mer och mer på mig... Hur rimligt är det egentligen att gifta sig på grund av praktiska skäl? Upplagt för katastrof eller är det bara positivt att se lite pragmatiskt på det hela?

**Comment by atifsheikh** [comment]
Error fixed, Need to upload the code.
