### ISSUE TITLE
Bygghus post message issue

### ISSUE THREAD

**Issue by Ripipip** [adfenix/orator#3]
The forum document is not properly configured for Byggahus forum. 

Orator url: http://www.orator.se/user-area/thread?id=200000230458&pg=1

Original url: http://www.byggahus.se/forum/bygglov/250543-behovs-bygglov-att-bygga-om-bodar.html

Message: Vad skulle konsekvenserna vara om man river och bygger nytt utan bygglov?

**Comment by atifsheikh** [comment]
Issue Fixed.

**Comment by atifsheikh** [comment]
Code uploaded, need verification from "Ripipip"
