### ISSUE TITLE
Sweclockers post message issue

### ISSUE THREAD

**Issue by Ripipip** [adfenix/orator#4]
The forum document is not properly configured for Sweclockers forum. Think it lacks cookie property. 

Orator url: http://www.orator.se/user-area/thread?id=200000230154&pg=1

Original url: http://www.sweclockers.com/forum/145-moln-och-internettjanster/1350739-program-att-sortera-olika-typer-av-data/

Message: Är det viktigast att datat visualiseras eller att det är enkelt att sätta upp?

**Comment by atifsheikh** [comment]
Bug fixed (just need to upload the code)

**Comment by atifsheikh** [comment]
Code Uploaded, need verification from "Ripipip"
